dbt_service:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: finny_user
      password: finny_password
      port: 4320
      dbname: finny_db
      schema: public
      threads: 32
      keepalives_idle: 0 # default 0, indicating the system default
      connect_timeout: 10 # default 10 seconds
      retries: 1  # default 1 retry on failure
      # This will create schemas like: raw, staging, marts
      search_path: "public"